<template>
  <div>
      <div class="wrapper">
          <ul>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
              <li>分类列表</li>
          </ul>
      </div>
  </div>
</template>

<script>
import BScroll  from 'better-scroll'
export default {
    name:'Category',
    data(){
        return{
            bscroll:null
        }
    },
    mounted(){
        this.bscroll=new BScroll(document.querySelector('.wrapper'),{
            probeType:3,
            click:true,
            pullUpLoad:true,
        }),
        this.bscroll.on('scroll',(pos)=>{
            console.log(pos)
        })
        this.bscroll.on('pullingUp',()=>{
            console.log('上拉加载更多')
        })
    }
}
</script>

<style>
    .wrapper{
        height:150px;
        background-color: skyblue;
        overflow: hidden;
    }
</style>